// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Infrastructure.Persistence.Context;

#nullable disable

namespace PersonalFinance.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_User_IsActive")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("AssignedAt");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRole_UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Config.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsGlobal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IsGlobal")
                        .HasDatabaseName("IX_Category_IsGlobal")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Category_UserId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Financial.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("DueDate");

                    b.Property<int>("FortnightType")
                        .HasColumnType("int")
                        .HasColumnName("FortnightTypeId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notes");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("PaymentDate");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatusId");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PeriodId");

                    b.Property<int>("SourceType")
                        .HasColumnType("int")
                        .HasColumnName("SourceTypeId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Expense_CategoryId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Expense_DueDate");

                    b.HasIndex("PaymentStatus")
                        .HasDatabaseName("IX_Expense_PaymentStatusId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("IX_Expense_PeriodId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Expense_UserId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Expense", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expense_Amount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Financial.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<int>("FortnightType")
                        .HasColumnType("int")
                        .HasColumnName("FortnightTypeId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notes");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PeriodId");

                    b.Property<DateOnly>("ReceivedAt")
                        .HasColumnType("date")
                        .HasColumnName("ReceivedAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("IX_Income_PeriodId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Income_UserId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Income", null, t =>
                        {
                            t.HasCheckConstraint("CK_Income_Amount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Financial.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("DeletedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("Month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Period_UserId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("Year", "Month")
                        .HasDatabaseName("IX_Period_YearMonth");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("UQ_Period_UserYearMonth");

                    b.ToTable("Period", null, t =>
                        {
                            t.HasCheckConstraint("CK_Period_Month", "[Month] BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Lookup.FortnightType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("FortnightType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "First"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Second"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Lookup.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Despesa pendente de pagamento",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Despesa paga",
                            Name = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Despesa cancelada",
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Despesa parcialmente paga",
                            Name = "Partial"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Lookup.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrador do sistema — acesso total",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Usuário padrão — acesso às próprias finanças",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Lookup.SourceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("SourceType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Parental"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("PersonalFinance.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Config.Category", b =>
                {
                    b.HasOne("PersonalFinance.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Financial.Expense", b =>
                {
                    b.HasOne("PersonalFinance.Domain.Entities.Config.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Domain.Entities.Financial.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Financial.Income", b =>
                {
                    b.HasOne("PersonalFinance.Domain.Entities.Financial.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Financial.Period", b =>
                {
                    b.HasOne("PersonalFinance.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
